name-template: 'next version'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '⚠️ Breaking Changes' 
    labels:
      - 'feat!:'
      - 'feat!('
  - title: '🚀 New Features'
    labels:
      - 'feat:'
      - 'feat('
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix:'
      - 'fix('
  - title: '🧰 Maintenance'
    labels:
      - 'refactor:'
      - 'refactor('
      - 'docs:'
      - 'docs('
exclude-labels:
  - 'chore:'
  - 'chore('
  - 'test:'
  - 'test('
  - 'style:'
  - 'style('
  - 'cosm:'
  - 'cosm('
  - 'build:'
  - 'build('
change-template: '* $TITLE (#$NUMBER)'
template: |
  $CHANGES
